// 더미 데이터 (API 붙이면 교체)
export const PROGRAMS = [
  {
    id: 1,
    name: "경북 청년 애꿈수당",
    region: "경상북도",
    domain: "현금성",
    ageMin: 19, ageMax: 34,
    incomeTier: "중위 150% 이하",
    employment: "무관",             // 무관/재직/미취업/자영업
    status: "진행중",               // 진행중/마감
    period: { start: "2025-01-01", end: "2025-12-31" },
    url: "https://www.gb.go.kr/",
    tags: ["취업지원","현금성","도비"],
    desc: "경북 청년의 취업·정착 지원.",
  },
  {
    id: 2,
    name: "김천시 청년 월세지원",
    region: "김천시",
    domain: "주거",
    ageMin: 19, ageMax: 39,
    incomeTier: "중위 150% 이하",
    employment: "무관",
    status: "진행중",
    period: { start: "2025-02-01", end: "2025-12-31" },
    url: "https://www.gc.go.kr/",
    tags: ["주거","월세","김천시"],
    desc: "월 최대 보조 지원 프로그램.",
  },
  {
    id: 3,
    name: "서울 청년수당",
    region: "서울특별시",
    domain: "현금성",
    ageMin: 19, ageMax: 34,
    incomeTier: "중위 150% 이하",
    employment: "미취업",
    status: "마감",
    period: { start: "2025-03-01", end: "2025-04-15" },
    url: "https://youth.seoul.go.kr/",
    tags: ["취업준비","현금성","서울"],
    desc: "구직활동 촉진 수당.",
  },
  {
    id: 4,
    name: "중소기업 취업청년 소득세 감면",
    region: "전국",
    domain: "세제",
    ageMin: 15, ageMax: 34,
    incomeTier: "무관",
    employment: "재직",
    status: "진행중",
    period: { start: "2024-01-01", end: "2026-12-31" },
    url: "https://www.nts.go.kr/",
    tags: ["세금감면","근로","국세청"],
    desc: "근로자 소득세 감면.",
  },
];
